"""Build history.json -- historical price vs intrinsic value over time.

Generates a time-series of market price alongside low/mid/high intrinsic-value bands
and key events that moved the stock.

Data sources (in priority order):
  1. --ticker TICKER [--assumptions PATH]: Real monthly closing prices from yfinance.
     Value bands derived from DCF assumptions (labeled as model-projected). This is
     the recommended path for publication-grade charts.
  2. --assumptions PATH (no ticker): SYNTHETIC history generated by compounding
     backwards from the DCF anchor point. Output carries _is_synthetic: true and a
     data quality warning. NOT suitable for publication -- use --ticker instead.
  3. No arguments: Hardcoded Micron (MU) illustrative example data.

    python build_history.py --ticker MU --assumptions ../templates/assumptions.example.json
    python build_history.py --ticker NVDA
    python build_history.py --assumptions ../templates/assumptions.example.json
    python build_history.py --output history.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone

# ── hardcoded illustrative data (schema demonstration only) ────────────────

HARDCODED_MU = {
    "_is_illustrative": True,
    "_data_quality_warning": (
        "ILLUSTRATIVE EXAMPLE DATA -- NOT REAL MARKET HISTORY. "
        "These figures are constructed for schema demonstration only. "
        "For real historical data, use --ticker TICKER to pull prices from yfinance."
    ),
    "company": "MU",
    "ticker": "MU",
    "dates": [
        "2023-01", "2023-07", "2024-01", "2024-07",
        "2025-01", "2025-07", "2026-01", "2026-06",
    ],
    "price": [55, 63, 85, 120, 95, 140, 350, 1134],
    "value_low": [40, 45, 55, 70, 80, 100, 250, 396],
    "value_mid": [60, 70, 90, 110, 130, 180, 400, 632],
    "value_high": [90, 100, 130, 160, 200, 280, 600, 868],
    "events": [
        {"date": "2023-09", "label": "HBM3E qualification", "impact": "positive"},
        {"date": "2024-03", "label": "AI server demand surge", "impact": "positive"},
        {"date": "2025-06", "label": "First $10B+ quarter", "impact": "positive"},
        {
            "date": "2025-12",
            "label": "16 SCAs signed, $22B+ commitments",
            "impact": "positive",
        },
        {
            "date": "2026-03",
            "label": "TurboQuant efficiency concerns",
            "impact": "negative",
        },
        {
            "date": "2026-06",
            "label": "Q3 FY2026: $41.5B revenue, 84.9% GM",
            "impact": "positive",
        },
    ],
}

# ── synthetic back-history (legacy path -- carries prominent warning) ───────

SYNTHETIC_WARNING = (
    "SYNTHETIC DATA -- NOT REAL MARKET HISTORY. "
    "This time series was mathematically generated by compounding backwards "
    "from a single DCF valuation anchor point at an assumed 20% pa growth rate. "
    "Price and value figures are FABRICATED and must not be mistaken for actual "
    "historical market data. Use --ticker TICKER to pull real prices from yfinance instead. "
    "Generated at: {timestamp}"
)


def _synthetic_history(path: str) -> dict:
    """Generate synthetic price/value history by compounding backwards from a
    single DCF valuation anchor point.

    ALL output values are mathematically fabricated. The output dict carries
    _is_synthetic: true and a prominent _data_quality_warning banner.

    This function is retained for rapid prototyping when real price data is
    unavailable. Prefer _from_yfinance() for any output that may be published
    or shared.
    """
    try:
        from valuation_inputs import load_inputs
        import dcf_valuation as dcf
    except ImportError:
        from scripts.valuation_inputs import load_inputs  # type: ignore
        from scripts import dcf_valuation as dcf  # type: ignore

    inp = load_inputs(path)
    mid_vps = dcf.value(inp).value_per_share

    # Synthetic back-history: step back 7 periods, growth ~20% pa
    dates = []
    prices = []
    v_low = []
    v_mid = []
    v_high = []
    for i, offset in enumerate([-7, -6, -5, -4, -3, -2, -1, 0]):
        yr = 2026 + offset // 2
        mo = "01" if offset % 2 == 0 else "07"
        dates.append(f"{yr}-{mo}")
        t = i / 7.0  # 0..1
        scale = 0.04 + t * 0.96
        prices.append(round(mid_vps * scale * 1.5))
        v_low.append(round(mid_vps * scale * 0.65))
        v_mid.append(round(mid_vps * scale))
        v_high.append(round(mid_vps * scale * 1.4))

    return {
        "_is_synthetic": True,
        "_data_quality_warning": SYNTHETIC_WARNING.format(
            timestamp=datetime.now(tz=timezone.utc).isoformat()
        ),
        "company": inp.company,
        "ticker": inp.company,
        "dates": dates,
        "price": prices,
        "value_low": v_low,
        "value_mid": v_mid,
        "value_high": v_high,
        "events": [],
    }


# ── yfinance real-price history (primary path) ─────────────────────────────

YFINANCE_UNAVAILABLE_MSG = (
    "yfinance is not installed. Install with: pip install yfinance"
)


def _from_yfinance(
    ticker: str, assumptions_path: str | None = None
) -> dict:
    """Fetch real monthly closing prices from yfinance and derive model-projected
    value bands from DCF assumptions.

    Returns a dict with:
      - dates: real calendar dates (YYYY-MM-DD), sampled monthly over ~5 years
      - price: real adjusted closing prices from yfinance
      - value_low/mid/high: model-projected bands. When assumptions_path is
        given, the current DCF value_per_share is computed and scaled backward
        using the ratio of historical price to current price (constant
        price-to-value gap assumption). These are NOT historical intrinsic
        values -- they are a mechanical projection for chart rendering only.
        Without assumptions, bands default to price (mid=price, low/high=±30%).
      - events: [] (empty -- event annotations are judgment inputs)

    The output carries _data_source and _value_band_method metadata describing
    exactly how every figure was derived.
    """
    try:
        import yfinance as yf
    except ImportError:
        return {
            "_error": "yfinance_not_installed",
            "_message": YFINANCE_UNAVAILABLE_MSG,
            "ticker": ticker,
        }

    try:
        t = yf.Ticker(ticker)
        # Monthly data for approximately 5 years
        hist = t.history(period="5y", interval="1mo")
        if hist.empty:
            return {
                "_error": "no_data",
                "_message": (
                    f"No price history available for ticker '{ticker}' "
                    f"from yfinance. The ticker may be delisted, invalid, "
                    f"or have insufficient trading history."
                ),
                "ticker": ticker,
            }
    except Exception as e:
        return {
            "_error": "yfinance_fetch_failed",
            "_message": f"Failed to fetch data for '{ticker}': {e}",
            "ticker": ticker,
        }

    # Build the base output with real prices
    dates_list = [d.strftime("%Y-%m-%d") for d in hist.index]
    prices_list = [round(float(p), 2) for p in hist["Close"]]
    current_price = prices_list[-1]

    result = {
        "_data_source": "yfinance",
        "_fetch_timestamp": datetime.now(tz=timezone.utc).isoformat(),
        "_data_quality_warning": (
            "Market prices from yfinance (third-party aggregator tier). "
            "Confirm against primary exchange data before publication. "
            "Value bands are model-projected -- see _value_band_method."
        ),
        "company": ticker,
        "ticker": ticker,
        "dates": dates_list,
        "price": prices_list,
        "events": [],
    }

    # Compute model-projected value bands if assumptions are provided
    if assumptions_path:
        try:
            from valuation_inputs import load_inputs
            import dcf_valuation as dcf
        except ImportError:
            from scripts.valuation_inputs import load_inputs  # type: ignore
            from scripts import dcf_valuation as dcf  # type: ignore

        try:
            inp = load_inputs(assumptions_path)
            dcf_value = dcf.value(inp).value_per_share

            if current_price > 0:
                # Scale value bands by the ratio of historical price to current
                # price, preserving the current price-to-value gap.  This is a
                # mechanical projection -- NOT historical intrinsic values.
                ratio = dcf_value / current_price
                result["value_mid"] = [
                    round(float(p) * ratio, 2) for p in prices_list
                ]
                result["value_low"] = [
                    round(v * 0.70, 2) for v in result["value_mid"]
                ]
                result["value_high"] = [
                    round(v * 1.35, 2) for v in result["value_mid"]
                ]
                result["_value_band_method"] = (
                    f"Model-projected bands (NOT historical intrinsic values). "
                    f"value_mid = historical close x (DCF value / current price), "
                    f"where DCF value_per_share = {dcf_value:.2f}, "
                    f"current price = {current_price:.2f}, "
                    f"ratio = {ratio:.4f}. "
                    f"value_low = mid x 0.70, value_high = mid x 1.35. "
                    f"Assumes a constant price-to-value gap ratio over the period."
                )
            else:
                result["_value_band_error"] = (
                    "Current price is zero or negative; cannot compute ratio."
                )
        except Exception as e:
            result["_value_band_error"] = f"DCF computation failed: {e}"

    # Fallback value bands: when no assumptions, band = price (neutral default)
    if "value_mid" not in result:
        if current_price > 0:
            result["value_mid"] = [round(float(p), 2) for p in prices_list]
            result["value_low"] = [
                round(float(p) * 0.70, 2) for p in prices_list
            ]
            result["value_high"] = [
                round(float(p) * 1.35, 2) for p in prices_list
            ]
            result["_value_band_method"] = (
                "DEFAULT BANDS (no DCF assumptions provided). "
                "value_mid = closing price (assumes market is fairly priced). "
                "value_low = price x 0.70, value_high = price x 1.35. "
                "These are mechanical defaults for chart rendering only. "
                "Provide --assumptions to derive model-backed bands."
            )
        else:
            result["value_mid"] = []
            result["value_low"] = []
            result["value_high"] = []
            result["_value_band_method"] = (
                "No bands: current price is zero or negative."
            )

    return result


# ── CLI ────────────────────────────────────────────────────────────────────

def _main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Build history.json for price-vs-value time series."
    )
    ap.add_argument(
        "--ticker",
        default=None,
        help=(
            "Stock ticker symbol (e.g., MU, NVDA, AAPL). Fetches real "
            "monthly closing prices from yfinance (~5 years). "
            "Requires: pip install yfinance."
        ),
    )
    ap.add_argument(
        "--assumptions",
        default=None,
        help=(
            "Path to assumptions JSON. With --ticker: used to derive "
            "model-projected value bands. Without --ticker: generates "
            "SYNTHETIC history (carries data quality warning -- prefer "
            "using --ticker for real data)."
        ),
    )
    ap.add_argument(
        "--output",
        default=None,
        help="Write JSON to this file instead of stdout.",
    )
    args = ap.parse_args(argv)

    if args.ticker:
        # ── Primary path: real prices from yfinance ─────────────────────
        data = _from_yfinance(args.ticker, args.assumptions)
        if "_error" in data:
            print(
                f"ERROR [{data['_error']}]: {data['_message']}",
                file=sys.stderr,
            )
            # Fall back to synthetic if assumptions are available
            if args.assumptions:
                print(
                    "Falling back to synthetic history "
                    "(data quality warning applies).",
                    file=sys.stderr,
                )
                data = _synthetic_history(args.assumptions)
            else:
                print(
                    "No assumptions file provided; cannot generate fallback. "
                    "Options: install yfinance (pip install yfinance), "
                    "or provide --assumptions for synthetic fallback.",
                    file=sys.stderr,
                )
                return 1
    elif args.assumptions:
        # ── Synthetic path (no ticker) -- explicitly warned ─────────────
        data = _synthetic_history(args.assumptions)
    else:
        # ── Hardcoded illustrative example ─────────────────────────────
        data = HARDCODED_MU

    text = json.dumps(data, indent=2)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.write("\n")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
